apiVersion: cloudwatch.aws.amazon.com/v1alpha1
kind: Instrumentation
metadata:
  name: java-instrumentation
spec:
  exporter:
    endpoint: http://cloudwatch-agent.amazon-cloudwatch:4317
  propagators:
    - tracecontext
    - baggage
    - b3
    - xray
  java:
    image: public.ecr.aws/aws-observability/adot-autoinstrumentation-java
    tag: latest
    env:
      - name: OTEL_METRICS_EXPORTER
        value: "none"
      - name: OTEL_SMP_ENABLED
        value: "true"
      - name: OTEL_TRACES_SAMPLER_ARG
        value: "0.05"
      - name: OTEL_TRACES_SAMPLER
        value: "parentbased_traceidratio"