apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: amazon-cloudwatch
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        instrumentation.opentelemetry.io/inject-java: "true"
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          args:
          - "--auto-instrumentation-java-image=public.ecr.aws/aws-observability/adot-autoinstrumentation-java:v1.31.1"
      restartPolicy: Always
status: {}