
---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "cloudwatchagent-operator.labels" . | nindent 4}}
  name: {{ template "cloudwatchagent-operator.webhookServiceName" . }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: {{ .Values.manager.ports.containerPort }}
  selector:
    app.kubernetes.io/name: {{ template "cloudwatchagent-operator.name" . }}
    control-plane: controller-manager
