apiVersion: cloudwatch.aws.amazon.com/v1alpha1
kind: AmazonCloudWatchAgent
metadata:
  name: cloudwatch-agent
  namespace: amazon-cloudwatch
spec:
  containers:
  - name: amazon-cloudwatch-agent
    image: amazon/cloudwatch-agent