# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

name: Run EKS op-int-test Integration Tests
env:
  TERRAFORM_AWS_ASSUME_ROLE: ${{ secrets.TERRAFORM_AWS_ASSUME_ROLE }}

on:
  push:
    branches:
      - main*
      - op-int-test
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

jobs:
  OperatorIntegrationTest:
    name: OperatorIntegrationTest
    runs-on: ubuntu-latest
    env:
      OPERATOR_IMAGE: ${{ secrets.ECR_OPERATOR_STAGING_IMAGE }}
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Image
        run: |
          docker build -t $OPERATOR_IMAGE .
          docker push $OPERATOR_IMAGE

      - name: Update manager.yaml
        run: |
          sed -i "s|name: controller.*|name: controller\n  newName: $OPERATOR_IMAGE|" path/to/manager.yaml

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -k path/to/manager.yaml

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ env.TERRAFORM_AWS_ASSUME_ROLE }}
          aws-region: us-west-2

      - name: Verify Terraform version
        run: terraform --version

      - name: Terraform apply
        uses: nick-fields/retry@v2
        with:
          max_attempts: 1
          timeout_minutes: 60 # EKS takes about 20 minutes to spin up a cluster and service on the cluster
          retry_wait_seconds: 5
          command: |
            cd integration-tests/terraform/testbuild

            terraform init
            if terraform apply --auto-approve; then
                cd -
                kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.12.0/cert-manager.yaml
                make deploy
                sleep 120
                kubectl describe deploy -n amazon-cloudwatch
                kubectl get pod -A
                kubectl get all -n amazon-cloudwatch
                kubectl get crd
            else
              terraform destroy -auto-approve && exit 1
            fi

      - name: Terraform destroy
        if: ${{ cancelled() || failure() }}
        uses: nick-fields/retry@v2
        with:
          max_attempts: 3
          timeout_minutes: 8
          retry_wait_seconds: 5
          command: |
            cd integration-tests/terraform/eks

            terraform destroy --auto-approve